data = {
"sourceTags": [],
        "wasteTags": [
            "含重金属（Pb）废液",
            "化学沾染物",
            "利器",
            "瓶装废试剂",
            "碎玻璃",
            "一般无机废液",
            "一般有机废液"
        ],
        "labTags": [
            "A701",
            "A702",
            "A703",
            "A704",
            "A705",
            "A706",
            "A707",
            "A708",
            "A709",
            "其他"
        ],
        "producerTags": [
            "Accela ChemBio",
            "Amresco",
            "Ark Pharm",
            "Chemicell",
            "Farco Pharma",
            "Frontier Scientific",
            "Gelest",
            "Haltermann Carless",
            "Sigma-Aldrich（Vetec）",
            "SPI Supplies",
            "Strem Chemicals",
            "Ted Pella",
            "阿拉丁（Aladdin）",
            "安徽泽升科技有限公司（安耐吉、Energy Chemical、3A Chemical）",
            "百灵威（J&K）",
            "北京奥博星公司",
            "北京大兴兴福精细化学研究所",
            "北京东环试剂厂",
            "北京房山新光试剂厂",
            "北京国华化学试剂厂",
            "北京国研科工实验器材有限公司",
            "北京红星化工厂",
            "北京鸿柏科技有限公司",
            "北京华威锐科化工有限公司",
            "北京华中海威基因科技有限公司（Harvey）",
            "北京化学工业集团有限公司（北京化工厂、北京新华试剂研究所）",
            "北京金龙化学试剂有限公司",
            "北京经科宏达生物技术有限公司",
            "北京酷来搏科技有限公司（CoolAber）",
            "北京迈瑞达科技有限公司（MREDA）",
            "北京石鹰化工有限公司（北京石鹰化工厂）",
            "北京市平谷双燕化工厂",
            "北京双环化学试剂厂",
            "北京索莱宝科技有限公司（Solarbio）",
            "北京天诺天诚生物科技有限公司（TNTC）",
            "北京通广精细化工公司",
            "北京沃凯生物科技有限公司（OKA）",
            "北京西中化工厂",
            "北京欣恒研科技有限公司",
            "北京欣经科生物公司",
            "北京欣熙源生物科技有限公司",
            "北京旭东化工有限公司",
            "北京伊诺凯科技有限公司（Innochem）",
            "北京益利精细化学品有限公司",
            "北京中镜科仪技术有限公司",
            "北京中联化工有限责任公司",
            "毕得医药（Bidepharm）",
            "碧云天（Beyotime）",
            "博飞美科（Perfemiker）",
            "常州新华活性材料研究所",
            "大连海鑫化工有限公司",
            "大连新意化工有限公司",
            "国药集团化学试剂有限公司（沪试）",
            "霍尼韦尔（Honeywell、Fluka）",
            "江苏艾康生物医药研发有限公司（Aikon）",
            "均利博生物",
            "兰溪城南福利化工厂",
            "麦克林（Macklin）",
            "默克（Merck）",
            "其他",
            "塞莫诗（Simoos）",
            "赛默飞（Thermo Scientific、Alfa Aesar、Acros Organics、Maybridge、Life Technologies）",
            "上海笛柏生物科技有限公司",
            "上海东联化学股份有限公司",
            "上海放射医学研究所",
            "上海共价化学科技有限公司",
            "上海皓鸿生物医药科技有限公司（乐研）",
            "上海河森电气有限公司（Hesen）",
            "上海沪试实验室器材股份有限公司",
            "上海化学试剂有限公司试剂一厂",
            "上海惠兴生化试剂有限公司",
            "上海吉至生化科技有限公司（Acmec Biochemical）",
            "上海康达氨基酸厂",
            "上海迈瑞尔生化科技有限公司（Meryer）",
            "上海三爱思试剂有限公司（上海试剂三厂）",
            "上海韶远化学科技有限公司",
            "上海泰坦科技股份有限公司（Titan、Adamas-beta、General-reagent、Greagent）",
            "上海宜山冶炼厂",
            "上海易恩化学技术有限公司（罗恩、Rhawn）",
            "上海源叶生物科技有限公司",
            "上海政翔化学试剂研究所",
            "试剂库",
            "梯希爱（TCI）",
            "天津艾达恒晟科技发展有限公司",
            "天津福晨化学试剂厂",
            "天津化学试剂有限公司",
            "天津津科生物科技有限责任公司",
            "天津市化学试剂三厂",
            "天津市化学试剂一厂",
            "天津市康科德科技有限公司",
            "天津市科密欧化学试剂有限公司",
            "天津市苏庄化学试剂厂",
            "天津市天河化学试剂厂",
            "天津塘沽邓中化工厂",
            "天津天泰精细化学品有限公司",
            "天津希恩思生化科技有限公司（Heowns）",
            "同仁化学（Dojindo）",
            "温州东升化工试剂厂",
            "无锡书弗仪器有限公司",
            "吴江市青云光明精细化工厂",
            "西陇科学股份有限公司",
            "中国科学院微生物研究所",
            "淄博永嘉化工有限公司",
            "紫晶化学（Amethyst Chemicals）",
            "自制"
        ],
        "locationTags": [
            "保干器",
            "冰柜",
            "贵金属抽屉",
            "耗材区",
            "其他",
            "试剂柜",
            "酸橱",
            "小试剂柜",
            "样品架第1段",
            "样品架第2段",
            "样品架第3段",
            "样品架第4段",
            "易制爆试剂柜",
            "自行保存"
        ]
}

sql_statements = []

for tag_type, options in data.items():
  for option in options:
    sql = f"INSERT INTO dictionary (type, options) VALUES ('{tag_type}', '{option}');"
    sql_statements.append(sql)  # Fix: Change "sql_statificates" to "sql_statements"

# To print SQL statements
for statement in sql_statements:
  print(statement)
